version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: nginx.${APP_ENV}.dockerfile
    depends_on:
      - django
      - node
    volumes:
      - ${MEDIA_ROOT}:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - flashy-cards-network
  node:
    container_name: node
    build:
      context: .
      dockerfile: node.${APP_ENV}.dockerfile
      args: 
        - REACT_APP_API_SERVER
        - REACT_APP_MEDIA_SERVER
    environment:
      - REACT_APP_MEDIA_SERVER=${REACT_APP_MEDIA_SERVER}
      - REACT_APP_API_SERVER=${REACT_APP_API_SERVER}
    ports:
      - "3000"
    networks:
      - flashy-cards-network
  django:
    container_name: django
    image: django
    build:
      context: .
      dockerfile: django.${APP_ENV}.dockerfile
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - MEDIA_ROOT=${MEDIA_ROOT}
    ports:
      - "8000"
    volumes:
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ./backend:/usr/src/app/
    networks:
      - flashy-cards-network
      - flashy-cards-db-network
  db:
    container_name: db
    image: db
    build:
      context: .
      dockerfile: mysql.dockerfile
    ports:
      - "3306"
    networks:
      - flashy-cards-db-network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./:/usr/src/app

networks:
  flashy-cards-network:
  flashy-cards-db-network:
