FROM node
COPY ./frontend/ /usr/src/app/
WORKDIR /usr/src/app
ARG REACT_APP_API_SERVER
ENV REACT_APP_API_SERVER=$REACT_APP_API_SERVER
ARG REACT_APP_MEDIA_SERVER
ENV REACT_APP_MEDIA_SERVER=$REACT_APP_MEDIA_SERVER
RUN npm install && npm install -g serve && npm run build
EXPOSE 3000
ENTRYPOINT serve -s build -p 3000
